import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  conceptSidebar: [
    'README',
    {
      type: 'category',
      label: 'Визуальные эксперименты',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'briefs'}],
    },
  ],
};

export default sidebars;
