import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  designSidebar: [
    {
      type: 'category',
      label: 'Начать здесь',
      collapsed: false,
      items: ['game-overview', 'core-loop', 'design-pillars'],
    },
    {
      type: 'category',
      label: 'Игрок и физический мир',
      items: [
        'camera-and-perspective',
        'exploration',
        'inventory-and-item-logistics',
        'ownership-and-infrastructure',
      ],
    },
    {
      type: 'category',
      label: 'Развитие и экономика',
      items: [
        'specialization',
        'economy-and-resources',
        'construction',
      ],
    },
    {
      type: 'category',
      label: 'Королевство',
      items: [
        'kingdoms-and-local-cooperation',
        'public-projects',
        'petitions',
      ],
    },
    {
      type: 'category',
      label: 'Сезон и победа',
      items: ['victory-conditions'],
    },
    {
      type: 'category',
      label: 'Состояние дизайна',
      collapsed: false,
      items: ['decisions', 'open-questions', 'backlog'],
    },
    {
      type: 'category',
      label: 'Работа над дизайном',
      items: ['README'],
    },
    {
      type: 'category',
      label: 'Thought experiments',
      link: {type: 'doc', id: 'thought-experiments/README'},
      items: [
        {
          type: 'category',
          label: 'Активные',
          collapsed: false,
          items: [
            'thought-experiments/active/TE-030-offensive-theses',
            'thought-experiments/active/TE-029-diversion-boundaries',
            'thought-experiments/active/TE-028-combat-and-death-requirement-theses',
            'thought-experiments/active/TE-007-extraction-and-construction-boundary',
            'thought-experiments/active/TE-005-forest-progression-breakthroughs',
            'thought-experiments/active/TE-003-physical-trade-and-logistics',
          ],
        },
        {
          type: 'category',
          label: 'Архив',
          items: [{type: 'autogenerated', dirName: 'thought-experiments/archive'}],
        },
        'thought-experiments/template',
      ],
    },
  ],
};

export default sidebars;
